### ISSUE TITLE
IndexError raised while runing the preprocess.py

### ISSUE THREAD

**Issue by rm-rf0** [harvardnlp/urnng#1]
Hi, 

Thanks for releasing the codes for URNNG!

But when I ran your codes with the full PTB (the first several lines of which matched with your sample datasets), I got an IndexError.

After running the following command,
```
python preprocess.py --trainfile data/train --valfile data/dev --testfile data/test --outputfile data/ptb --vocabminfreq 1 --lowercase 0 --replace_num 0 --batchsize 16
```

I got:
```python
First pass through data to get vocab...
Number of sentences in training: 45445
Number of sentences in valid: 1346
Number of sentences in test: 2416
Vocab size: Original = 47451, Pruned = 25573
141 116 67
2416 2416
2416 2416
Saved 2416 sentences (dropped 0 due to length/unk filter)
1346 1346
1346 1346
Saved 1346 sentences (dropped 0 due to length/unk filter)
Traceback (most recent call last):
  File "preprocess.py", line 344, in <module>
    sys.exit(main(sys.argv[1:]))
  File "preprocess.py", line 341, in main
    get_data(args)
  File "preprocess.py", line 305, in get_data
    max_sent_l, args.shuffle, args.include_boundary, 1)
  File "preprocess.py", line 208, in convert
    sents[sent_id] = np.array(indexer.convert_sequence(sent_pad), dtype=int)
IndexError: index 45445 is out of bounds for axis 0 with size 45445
```

**Comment by yoonkim** [comment]
Ah thanks for posting this. Should be fixed now. Basically the issue was that if a sentence length was > max sequence length, it was not being properly ignored. 

By the way, I think the training set should be 39832 sentences?

**Comment by rm-rf0** [comment]
I am not sure... Probably because that I have section 00 and section 01 of the WSJ included?

My first sentence is:

```
(S (NP (NP (NNP Pierre) (NNP Vinken)) (, ,) (ADJP (NP (CD 61) (NNS years)) (JJ old)) (, ,)) (VP (MD will) (VP (VB join) (NP (DT the) (NN board)) (PP (IN as) (NP (DT a) (JJ nonexecutive) (NN director))) (NP (NNP Nov.) (CD 29)))) (. .))
```
The first sentence in your sample training set is the 3915th sentence of mine.

Also, I have sentences which don't start with `(S `, e.g

```
(SINV (`` ``) (S (NP (PRP We)) (VP (VBP have) (NP (NP (DT no) (JJ useful) (NN information)) (PP (IN on) (SBAR (IN whether) (S (NP (NNS users)) (VP (VBP are) (PP (IN at) (NP (NN risk)))))))))) (, ,) ('' '') (VP (VBD said)) (NP (NP (NNP James) (NNP A.) (NNP Talcott)) (PP (IN of) (NP (NP (NNP Boston) (POS 's)) (NNP Dana-Farber) (NNP Cancer) (NNP Institute)))) (. .))
```

```
(FRAG (NP (RB Just) (DT the) (NN thing)) (PP (IN for) (NP (NP (DT the) (JJ Vivaldi-at-brunch) (NN set)) (, ,) (NP (NP (DT the) (NN yuppie) (NN audience)) (SBAR (WHNP (WDT that)) (S (VP (VBZ has) (VP (VBN embraced) (NP (NNP New) (NNP Age)) (PP (IN as) (NP (PRP$ its) (ADJP (RB very) (JJ own)) (JJ easy) (NN listening)))))))))) (. .))
```

I also find that I have nonbinary trees included.

**Comment by yoonkim** [comment]
Yeah, I believe the standard PTB train set starts from section 02
